packages:
  - '.'
allowBuilds:
  better-sqlite3: true
minimumReleaseAgeExclude:
  - '@expo/cli@55.0.31'
  - '@expo/metro-config@55.0.22'
  - '@expo/router-server@55.0.17'
  - babel-preset-expo@55.0.22
  - expo-file-system@55.0.21
  - expo-font@55.0.8
  - expo-modules-autolinking@55.0.23
  - expo-server@55.0.10
  - expo@55.0.25
  - expo-dev-client@55.0.35
  - expo-dev-launcher@55.0.36
  - expo-dev-menu@55.0.30
  - expo-updates@55.0.23
